openapi: 3.0.0
info:
  title: gyms
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/gyms:
    get:
      summary: Get all gyms
      tags:
        - gyms
      responses: {}
      operationId: get-api-gyms
components:
  schemas: {}
