openapi: 3.0.0
info:
  title: gyms
  version: '1.0'
  description: API endpoint to retrieve all gym related requests
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/gyms/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: Get gym with id
      tags: []
      operationId: get-gyms-id
      description: Retrieves the gym with the provided id
  /api/gyms/search:
    get:
      summary: Search for gym by name
      tags: []
      responses: {}
      operationId: get-api-gyms-search
      parameters:
        - schema:
            type: string
          in: query
          name: name
          required: true
          description: The name of the gym
      description: Retrieves the gym whose name matches the search string
  /api/gyms/range:
    get:
      summary: Gets gyms within distance range
      tags: []
      responses: {}
      operationId: get-api-gyms-range
      parameters:
        - schema:
            type: number
            format: double
          in: query
          name: latitude
          required: true
        - schema:
            type: number
            format: double
          in: query
          name: longitude
          required: true
        - schema:
            type: number
            format: double
            exclusiveMinimum: true
          in: query
          name: radius
          required: true
          description: 'Radius away from (latitude, longitude) in miles'
      description: Retrieves the gyms that are at most `radius` miles away from the `latitude` and `longitude` position
  /api/gyms/open:
    get:
      summary: Gyms open at time
      tags: []
      responses: {}
      operationId: get-api-gyms-open
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: time
          description: A Unix Timestamp
      description: Retrieves the gyms that are open now (default) or at the provided timestamp
  /api/gyms:
    get:
      summary: Gets all gyms
      tags: []
      responses: {}
      operationId: get-api-gyms
      description: Retrieves all gyms
components:
  schemas: {}
