openapi: 3.0.0
info:
  title: gyms
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/gyms/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: Get gym with id
      tags: []
      responses: {}
      operationId: get-gyms-id
  /api/gyms/search:
    get:
      summary: Search for gym by name
      tags: []
      responses: {}
      operationId: get-api-gyms-search
      parameters:
        - schema:
            type: string
          in: query
          name: name
          required: true
  /api/gyms/range:
    get:
      summary: Gets gyms within distance range
      tags: []
      responses: {}
      operationId: get-api-gyms-range
      parameters:
        - schema:
            type: number
          in: query
          name: latitude
          required: true
        - schema:
            type: number
          in: query
          name: longitude
          required: true
        - schema:
            type: number
          in: query
          name: radius
          required: true
  /api/gyms/open:
    get:
      summary: Gyms open at time
      tags: []
      responses: {}
      operationId: get-api-gyms-open
      parameters:
        - schema:
            type: integer
          in: query
          name: time
  /api/gyms:
    get:
      summary: Gets all gyms
      tags: []
      responses: {}
      operationId: get-api-gyms
components:
  schemas: {}
