openapi: 3.0.0
info:
  title: transit
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    route:
      title: route
      type: object
      description: Model for AC Transit Route
      properties:
        route_id:
          type: integer
        name:
          type: string
        description:
          type: string
    stop:
      title: stop
      type: object
      description: Model for AC Transit Stop
      properties:
        stop_id:
          type: integer
        name:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        schedule_time:
          type: integer
