openapi: 3.0.0
info:
  title: weather
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/weather:
    get:
      summary: Gets the weather for Berkeley
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/weather-model'
              examples:
                example-1:
                  value:
                    lat: 40.12
                    lon: -96.66
                    timezone: America/Chicago
                    timezone_offset: -18000
                    current:
                      dt: 1595243443
                      sunrise: 1595243663
                      sunset: 1595296278
                      temp: 293.28
                      feels_like: 293.82
                      pressure: 1016
                      humidity: 100
                      dew_point: 293.28
                      uvi: 10.64
                      clouds: 90
                      visibility: 10000
                      wind_speed: 4.6
                      wind_deg: 310
                      weather:
                        - id: 501
                          main: Rain
                          description: moderate rain
                          icoan: 10n
                        - id: 201
                          main: Thunderstorm
                          description: thunderstorm with rain
                          icon: 11n
                      rain:
                        1h: 2.93
                    minutely:
                      - dt: 1595243460
                        precipitation: 2.928
                    hourly:
                      - dt: 1595242800
                        temp: 293.28
                        feels_like: 293.82
                        pressure: 1016
                        humidity: 100
                        dew_point: 293.28
                        clouds: 90
                        visibility: 10000
                        wind_speed: 4.6
                        wind_deg: 123
                        weather:
                          - id: 501
                            main: Rain
                            description: moderate rain
                            icon: 10n
                        pop: 0.99
                        rain:
                          1h: 2.46
                    daily:
                      - dt: 1595268000
                        sunrise: 1595243663
                        sunset: 1595296278
                        temp:
                          day: 298.82
                          min: 293.25
                          max: 301.9
                          night: 293.25
                          eve: 299.72
                          morn: 293.48
                        feels_like:
                          day: 300.06
                          night: 292.46
                          eve: 300.87
                          morn: 293.75
                        pressure: 1014
                        humidity: 82
                        dew_point: 295.52
                        wind_speed: 5.22
                        wind_deg: 146
                        weather:
                          - id: 502
                            main: Rain
                            description: heavy intensity rain
                            icon: 10d
                        clouds: 97
                        pop: 1
                        rain: 12.57
                        uvi: 10.64
                    alerts:
                      - sender_name: NWS Tulsa (Eastern Oklahoma)
                        event: Heat Advisory
                        start: 1597341600
                        end: 1597366800
                        description: |-
                          ...HEAT ADVISORY REMAINS IN EFFECT FROM 1 PM THIS AFTERNOON TO
                          8 PM CDT THIS EVENING...
                          * WHAT...Heat index values of 105 to 109 degrees expected.
                          * WHERE...Creek, Okfuskee, Okmulgee, McIntosh, Pittsburg,
                          Latimer, Pushmataha, and Choctaw Counties.
                          * WHEN...From 1 PM to 8 PM CDT Thursday.
                          * IMPACTS...The combination of hot temperatures and high
                          humidity will combine to create a dangerous situation in which
                          heat illnesses are possible.
      operationId: get-api-weather
      description: 'Get the weather for Berkeley, CA'
components:
  schemas:
    weather-model:
      description: ''
      type: object
      properties:
        lat:
          type: number
        lon:
          type: number
        timezone:
          type: string
          minLength: 1
        timezone_offset:
          type: number
        current:
          type: object
          properties:
            dt:
              type: number
            sunrise:
              type: number
            sunset:
              type: number
            temp:
              type: number
            feels_like:
              type: number
            pressure:
              type: number
            humidity:
              type: number
            dew_point:
              type: number
            uvi:
              type: number
            clouds:
              type: number
            visibility:
              type: number
            wind_speed:
              type: number
            wind_deg:
              type: number
            weather:
              type: array
              uniqueItems: true
              minItems: 1
              items:
                type: object
                properties:
                  id:
                    type: number
                  main:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                  icoan:
                    type: string
                    minLength: 1
            rain:
              type: object
              properties:
                1h:
                  type: number
        minutely:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              dt:
                type: number
              precipitation:
                type: number
        hourly:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              dt:
                type: number
              temp:
                type: number
              feels_like:
                type: number
              pressure:
                type: number
              humidity:
                type: number
              dew_point:
                type: number
              clouds:
                type: number
              visibility:
                type: number
              wind_speed:
                type: number
              wind_deg:
                type: number
              weather:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    main:
                      type: string
                      minLength: 1
                    description:
                      type: string
                      minLength: 1
                    icon:
                      type: string
                      minLength: 1
              pop:
                type: number
              rain:
                type: object
                properties:
                  1h:
                    type: number
        daily:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              dt:
                type: number
              sunrise:
                type: number
              sunset:
                type: number
              temp:
                type: object
                properties:
                  day:
                    type: number
                  min:
                    type: number
                  max:
                    type: number
                  night:
                    type: number
                  eve:
                    type: number
                  morn:
                    type: number
              feels_like:
                type: object
                properties:
                  day:
                    type: number
                  night:
                    type: number
                  eve:
                    type: number
                  morn:
                    type: number
              pressure:
                type: number
              humidity:
                type: number
              dew_point:
                type: number
              wind_speed:
                type: number
              wind_deg:
                type: number
              weather:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    main:
                      type: string
                      minLength: 1
                    description:
                      type: string
                      minLength: 1
                    icon:
                      type: string
                      minLength: 1
              clouds:
                type: number
              pop:
                type: number
              rain:
                type: number
              uvi:
                type: number
        alerts:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              sender_name:
                type: string
                minLength: 1
              event:
                type: string
                minLength: 1
              start:
                type: number
              end:
                type: number
              description:
                type: string
                minLength: 1
