openapi: 3.0.0
info:
  title: weather
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/weather:
    get:
      summary: Gets the weather for Berkeley
      tags: []
      responses: {}
      operationId: get-api-weather
components:
  schemas: {}
